global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-backend'
    static_configs:
      - targets: ['backend:5000']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']